drop table reparto;
drop table peliculas;
CREATE TABLE peliculas (id INT, pelicula VARCHAR(100),año_estreno INT, director VARCHAR(100),PRIMARY KEY (id));
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('1','Forest Gump','1994','Robert Zemeckis');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('2','Titanic','1997','James Cameron');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('3','El Padrino','1972','Francis Ford Coppola');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('4','Gladiator','2000','Ridley Scott');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('5','El SeÃ±or de los anillos: El retorno del rey','2003','Peter Jackson');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('6','El caballero oscuro','2008','Christopher Nolan');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('7','Cadena perpetua','1994','Frank Darabont');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('8','Piratas del Caribe: La maldiciÃ³n de la Perla Negra','2003','Gore Verbinski');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('9','Braveheart','1995','Mel Gibson');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('10','La lista de Schindler','1993','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('11','Toy Story','1995','John Lasseter');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('12','Eduardo Manostijeras','1990','Tim Burton');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('13','El SeÃ±or de los anillos: La comunidad del anillo','2001','Peter Jackson');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('14','Salvar al soldado Ryan','1998','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('15','Regreso al futuro','1985','Robert Zemeckis');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('16','Monstruos S.A.','2001','Pete Docter');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('17','Buscando a Nemo','2003','Andrew Stanton');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('18','El SeÃ±or de los anillos: Las dos torres','2002','Peter Jackson');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('19','Harry Potter y el Prisionero de Azkaban','2004','Alfonso CuarÃ³n');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('20','American History X','1998','Tony Kaye');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('21','300','2007','Zack Snyder');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('22','El sexto sentido','1999','M. Night Shyamalan');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('23','Pulp Fiction','1994','Quentin Tarantino');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('24','V de Vendetta','2005','James McTeigue');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('25','El silencio de los corderos','1991','Jonathan Demme');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('26','Rocky','1976','John G. Avildsen');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('27','El club de la pelea','1999','David Fincher');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('28','E.T','1982','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('29','Parque Jurasico','1993','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('30','Matrix','1999','Andy y Lana Wachowski');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('31','La milla verde','1999','Frank Darabont');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('32','Ratatouille','2007','Brad Bird');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('33','Grease','1978','Randal Kleiser');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('34','El Padrino. Parte II','1974','Francis Ford Coppola');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('35','Wall-E','2008','Andrew Stanton');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('36','Iron Man','2008','Jon Favreau');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('37','El exorcista','1973','William Friedkin');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('38','Piratas del Caribe: El cofre del hombre muerto','2006','Gore Verbinski');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('39','Seven','1995','David Fincher');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('40','Terminator 2: el juicio final','1991','James Cameron');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('41','El resplandor','1980','Stanley Kubrick');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('42','Hombres de negro','1997','Barry Sonnenfeld');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('43','Spider-Man','2002','Sam Raimi');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('44','Regreso al futuro II','1989','Robert Zemeckis');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('45','El show de Truman','1998','Peter Weir');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('46','Toy Story 2','1999','John Lasseter');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('47','Pesadilla antes de navidad','1993','Henry Selick');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('48','Star Wars. Episodio IV: Una nueva esperanza','1977','George Lucas');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('49','Saw','2004','James Wan');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('50','Terminator','1984','James Cameron');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('51','Kill Bill Vol. 1','2003','Quentin Tarantino');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('52','Lo que el viento se llevÃ³','1939','Victor Fleming');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('53','El Laberinto del Fauno','2006','Guillermo del Toro');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('54','Los increÃ­bles','2004','Brad Bird');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('55','El viaje de Chihiro','2001','Hayao Miyazaki');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('56','El precio del poder','1983','Brian De Palma');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('57','King Kong','2005','Peter Jackson');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('58','Ben-Hur','1959','William Wyler');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('59','Indiana Jones y la Ãºltima cruzada','1989','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('60','Infiltrados','2006','Martin Scorsese');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('61','Entrevista con el vampiro','1994','Neil Jordan');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('62','Batman Begins','2005','Christopher Nolan');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('63','En busca del arca perdida','1981','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('64','Star Wars. Episodio III: La venganza de los Sith','2005','George Lucas');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('65','Alien','1979','Ridley Scott');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('66','El bueno el feo y el malo','1966','Sergio Leone');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('67','Star Wars. Episodio V: El imperio contraataca','1980','Irvin Kershner');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('68','El Padrino. Parte III','1990','Francis Ford Coppola');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('69','Star Wars. Episodio VI: El retorno del Jedi','1983','Richard Marquand');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('70','Escuela de Rock','2003','Richard Linklater');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('71','El planeta de los simios','1968','Franklin J. Schaffner');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('72','Rambo','1982','Ted Kotcheff');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('73','Full Metal Jacket','1987','Stanley Kubrick');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('74','TiburÃ³n','1975','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('75','El profesional','1994','Luc Besson');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('76','American Beauty','1999','Sam Mendes');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('77','Casablanca','1942','Michael Curtiz');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('78','AmÃ©lie','2001','Jean-Pierre Jeunet');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('79','Trainspotting','1996','Danny Boyle');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('80','axi driver','1976','Martin Scorsese');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('81','Alguien volÃ³ sobre el nido del cuco','1975','Milos Forman');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('82','Kill Bill Vol. 2','2004','Quentin Tarantino');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('83','Spider-Man 2','2004','Sam Raimi');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('84','X-Men 2','2003','Bryan Singer');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('85','Transformers','2007','Michael Bay');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('86','Star Wars. Episodio I: La amenaza fantasma','1999','George Lucas');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('87','Blade Runner','1982','Ridley Scott');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('88','Apocalypse Now','1979','Francis Ford Coppola');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('89','Mejor... imposible','1997','James L. Brooks');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('90','La vida de Brian','1979','Terry Jones');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('91','El libro de la selva','1967','Wolfgang Reitherman');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('92','Los cazafantasmas','1984','Ivan Reitman');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('93','Sweeney Todd: El barbero diabÃ³lico de la calle Fleet','2007','Tim Burton');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('94','Ocean''s Eleven','2001','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('95','Blancanieves y los siete enanitos','1937','David Hand');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('96','Predator','1987','John McTiernan');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('97','Indiana Jones y el templo maldito','1984','Steven Spielberg');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('98','Uno de los nuestros','1990','Martin Scorsese');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('99','Mouling Rouge','2001','Baz Luhrmann');
Insert into SYSTEM.PELICULAS (ID,PELICULA,"AÑO_ESTRENO",DIRECTOR) values ('100','Psicosis','1960','Alfred Hitchcock');
CREATE TABLE reparto (id_pelicula INT, actor VARCHAR(100),FOREIGN KEY (id_pelicula)REFERENCES peliculas(id));
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Robin Wright Penn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Gary Sinise');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Mykelti Williamson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Sally Field');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Rebecca Williams');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Michael Conner Humphreys');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Harold G. Herthum');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Haley Joel Osment');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','George Kelly');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Bob Penny');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','John Randall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Sam Anderson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Margo Moorer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Ione M. Telech');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('1','Christine Seabrook');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Leonardo DiCaprio');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Kate Winslet');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Billy Zane');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Kathy Bates');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Frances Fisher');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Bernard Hill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Jonathan Hyde');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Danny Nucci');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','David Warner');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Bill Paxton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Gloria Stuart');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Victor Garber');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('2','Suzy Amis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Marlon Brando');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Al Pacino');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','James Caan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Robert Duvall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Diane Keaton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','John Cazale');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Talia Shire');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Richard Castellano');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Sterling Hayden');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Gianni Russo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Rudy Bond');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','John Marley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Richard Conte');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Al Lettieri');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Abe Vigoda');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('3','Franco Citti');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Russell Crowe');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Joaquin Phoenix');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Connie Nielsen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Oliver Reed');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Richard Harris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Derek Jacobi');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Djimon Hounsou');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','David Schofield');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','John Shrapnel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Tomas Arana');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Ralf Moeller');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Spencer Treat Clark');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','David Hemmings');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Tommy Flanagan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Sven-Ole Thorsen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('4','Tony Curran');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Elijah Wood');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Viggo Mortensen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Ian McKellen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Sean Astin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Andy Serkis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','John Rhys-Davies');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Orlando Bloom');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','John Noble');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Miranda Otto');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','David Wenham');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Bernard Hill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Billy Boyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Dominic Monaghan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Liv Tyler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Karl Urban');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Ian Holm');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Hugo Weaving');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Cate Blanchett');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('5','Lawrence Makoare');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Christian Bale');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Heath Ledger');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Aaron Eckhart');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Michael Caine');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Gary Oldman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Maggie Gyllenhaal');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Morgan Freeman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Eric Roberts');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Cillian Murphy');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Anthony Michael Hall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Michael Jai White');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','William Fichtner');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Edison Chen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Monique Curnen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Chin Han');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Nestor Carbonell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Ritchie Coster');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Keith Szarabajka');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Colin McFarlane');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Melinda McGraw');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Nathan Gamble');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('6','Michael Vieau');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','Tim Robbins');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','Morgan Freeman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','Bob Gunton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','James Whitmore');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','Gil Bellows');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','William Sadler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','Mark Rolston');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('7','Clancy Brown');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Johnny Depp');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Geoffrey Rush');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Orlando Bloom');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Keira Knightley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Jonathan Pryce');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Jack Davenport');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Mackenzie Crook');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Zoe Saldana');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('8','Kevin R. McNally');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9',' Mel Gibson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Sophie Marceau');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Patrick McGoohan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Catherine McCormack');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','James Cosmo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Brendan Gleeson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Brian Cox');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Peter Mullan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Gerard McSorley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('9','Angus MacFadyen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('10','Liam Neeson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('10','Ben Kingsley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('10','Ralph Fiennes');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('10','Caroline Goodall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('10','Jonathan Sagall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('10','Embeth Davidtz');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('11','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Johnny Depp');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Winona Ryder');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Dianne Wiest');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Anthony Michael Hall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Alan Arkin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Kathy Baker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Vincent Price');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Caroline Aaron');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('12','Robert Oliveri');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Elijah Wood');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Ian McKellen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Viggo Mortensen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Sean Astin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Sean Bean');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Cate Blanchett');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Hugo Weaving');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Liv Tyler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Ian Holm');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Christopher Lee');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','John Rhys-Davies');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Orlando Bloom');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Dominic Monaghan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Billy Boyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Lawrence Makoare');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Craig Parker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Marton Csokas');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('13','Andy Serkis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Tom Hanks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Tom Sizemore');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Edward Burns');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Barry Pepper');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Adam Goldberg');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Vin Diesel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Giovanni Ribisi');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Jeremy Davies');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Matt Damon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Ted Danson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Paul Giamatti');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Dennis Farina');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Joerg Stadler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Max Martini');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Dylan Bruno');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('14','Bryan Cranston');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Michael J. Fox');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Christopher Lloyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Lea Thompson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Crispin Glover');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Claudia Wells');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Thomas F. Wilson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Billy Zane');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('15','Sachi Parker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('16','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('17','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Elijah Wood');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Viggo Mortensen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Ian McKellen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Sean Astin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Andy Serkis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','John Rhys-Davies');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Orlando Bloom');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Bernard Hill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Miranda Otto');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','David Wenham');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Dominic Monaghan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Billy Boyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Christopher Lee');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Liv Tyler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Karl Urban');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Brad Dourif');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Hugo Weaving');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Cate Blanchett');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('18','Craig Parker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Daniel Radcliffe');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Rupert Grint');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Emma Watson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Michael Gambon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Gary Oldman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Timothy Spall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Tom Felton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','David Thewlis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Dawn French');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Emma Thompson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Julie Christie');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Robbie Coltrane');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Peter Best');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Julie Walters');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Maggie Smith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Alan Rickman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Richard Griffiths');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Fiona Shaw');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Bonnie Wright');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Mark Williams');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Chris Rankin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','David Bradley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Oliver Phelps');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','James Phelps');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Matthew Lewis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Devon Murray');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Jamie Waylett');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Josh Herdman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Alfie Enoch');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Miriam Margolyes');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Gemma Jones');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Harry Melling');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Robert Hardy');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Warwick Davis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Edward Randell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Pam Ferris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Emily Da le');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Danielle Tabor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Jimmy Gardner');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Lenny Henry');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Lee Ingleby');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Adrian Rawlins');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('19','Geraldine Somerville');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Edward Norton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Edward Furlong');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Fairuza Balk');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Stacy Keach');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Elliott Gould');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Avery Brooks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Beverly D''Angelo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Jennifer Lien');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Guy Torry');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Ethan Suplee');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('20','Keram Malicki-Sanchez');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Gerard Butler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Lena Headey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','David Wenham');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Dominic West');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Vincent Regan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Rodrigo Santoro');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Michael Fassbender');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Andrew Tieman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Andrew Pleavin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Tom Wisdom');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Tim Conolly');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Tyler Max Neitzel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Mercedes Leggett');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('21','Peter Mensah');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Bruce Willis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Toni Collette');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Haley Joel Osment');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Olivia Williams');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Trevor Morgan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Donnie Wahlberg');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Peter Tambakis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Jeffrey Zubernis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','Bruce Norris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('22','KaDee Strickland');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','John Travolta');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Samuel L. Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Uma Thurman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Bruce Willis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Harvey Keitel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Eric Stoltz');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Tim Roth');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Maria de Medeiros');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Amanda Plummer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Ving Rhames');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Rosanna Arquette');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Christopher Walken');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Quentin Tarantino');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Peter Greene');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('23','Phil LaMarr');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Natalie Portman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Hugo Weaving');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Stephen Rea');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','John Hurt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Stephen Fry');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Rupert Graves');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Tim Pigott-Smith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Roger Allam');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Ben Miles');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Sinead Cusack');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Natasha Wightman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Eddie Marsan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('24','Billie Cook');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Jodie Foster');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Anthony Hopkins');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Scott Glenn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Ted Levine');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Anthony Heald');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Diane Baker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Brooke Smith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Tracey Walter');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Kasi Lemmons');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Chris Isaak');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Roger Corman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Frankie Faison');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('25','Paul Lazar');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('26','Sylvester Stallone');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('26','Talia Shire');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('26','Burt Young');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('26','Carl Weathers');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('26','Burgess Meredith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('26','Thayer David');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('26','Joe Spinell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Brad Pitt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Edward Norton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Helena Bonham Carter');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Meat Loaf');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Jared Leto');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Van Quattro');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Markus Redmond');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Michael Girardin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Rachel Singer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('27','Eion Bailey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','Henry Thomas');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','Dee Wallace');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','Robert MacNaughton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','Drew Barrymore');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','Peter Coyote');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','C. Thomas Howell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','K.C. Martel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','Sean Frye');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('28','Erika Eleniak');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Sam Neill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Laura Dern');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Jeff Goldblum');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Richard Attenborough');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Ariana Richards');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Joseph Mazzello');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Wayne Knight');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Samuel L. Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Bob Peck');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','Martin Ferrero');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('29','B.D. Wong');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Keanu Reeves');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Laurence Fishburne');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Carrie-Anne Moss');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Hugo Weaving');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Joe Pantoliano');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Marcus Chong');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Paul Goddard');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('30','Gloria Foster');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Tom Hanks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Michael Clarke Duncan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','David Morse');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Michael Jeter');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Doug Hutchison');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Sam Rockwell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Barry Pepper');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Jeffrey DeMunn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Bonnie Hunt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','James Cromwell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Graham Greene');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Gary Sinise');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Harry Dean Stanton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Patricia Clarkson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','William Sadler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('31','Paula Malcomson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('32','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','John Travolta');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Olivia Newton-John');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Stockard Channing');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Jeff Conaway');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Didi Conn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Lorenzo Lamas');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Dinah Manoff');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Barry Pearl');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('33','Michael Tucci');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Al Pacino');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Robert De Niro');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Diane Keaton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Robert Duvall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','James Caan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','John Cazale');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Lee Strasberg');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Talia Shire');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Marianna Hill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Danny Aiello');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Harry Dean Stanton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Troy Donahue');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Roger Corman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('34','Morgana King');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('35','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Robert Downey Jr.');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Terrence Howard');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Gwyneth Paltrow');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Jeff Bridges');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Stan Lee');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Leslie Bibb');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Clark Gregg');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Shaun Toub');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Faran Tahir');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('36','Samuel L. Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Linda Blair');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Max von Sydow');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Ellen Burstyn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Jason Miller');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Lee J. Cobb');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Kitty Winn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Jack MacGowran');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Arthur Storch');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Barton Heyman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('37','Gina Petrushka');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Johnny Depp');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Orlando Bloom');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Keira Knightley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Stellan SkarsgÃ¥rd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Bill Nighy');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Naomie Harris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Jonathan Pryce');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Jack Davenport');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Lee Arenberg');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Mackenzie Crook');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Kevin McNally');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('38','Geoffrey Rush');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','Brad Pitt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','Morgan Freeman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','Gwyneth Paltrow');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','Kevin Spacey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','John C. McGinley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','Richard Roundtree');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','R. Lee Ermey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','Leland Orser');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('39','Richard Schiff');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('40','Arnold Schwarzenegger');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('40','Linda Hamilton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('40','Edward Furlong');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('40','Robert Patrick');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('40','Earl Boen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('40','Joe Morton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('40','Jenette Goldstein');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Jack Nicholson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Shelley Duvall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Danny Lloyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Scatman Crothers');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Barry Nelson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Philip Stone');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Joe Turkel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Lia Beldman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Billie Gibson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Barry Denne');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','David Baxt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Manning Redwood');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Kisa Burns');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Louise Burns');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Alison Coleridge');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('41','Norman Gay');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Tommy Lee Jones');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Will Smith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Linda Fiorentino');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Vincent D''Onofrio');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Sergio CalderÃ³n');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Rip Torn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Siobhan Fallon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Tony Shalhoub');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('42','Verne Troyer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Tobey Maguire');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Kirsten Dunst');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Willem Dafoe');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','James Franco');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Rosemary Harris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Cliff Robertson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','J.K. Simmons');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Bruce Campbell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Bill Nunn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('43','Stan Lee');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Michael J. Fox');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Christopher Lloyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Lea Thompson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Thomas F. Wilson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Elisabeth Shue');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Charles Fleischer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Joe Flaherty');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Harry Waters Jr.');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('44','Billy Zane');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('45','Jim Carrey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('45','Laura Linney');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('45','Noah Emmerich');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('45','Natascha McElhone');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('45','Ed Harris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('45','Holland Taylor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('45','Paul Giamatti');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('46','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('47','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Mark Hamill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Carrie Fisher');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Peter Cushing');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Alec Guinness');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','David Prowse');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Peter Mayhew');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Anthony Daniels');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Kenny Baker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Phil Brown');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Shelagh Fraser');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Alex McCrindle');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('48','Jack Purvis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Cary Elwes');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Leigh Whannell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Danny Glover');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Monica Potter');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Dina Meyer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Tobin Bell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Shawnee Smith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Ken Leung');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Alexandra Bokyun Chun');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('49','Michael Emerson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Arnold Schwarzenegger');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Linda Hamilton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Michael Biehn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Paul Winfield');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Lance Henriksen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Rick Rossovich');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Bess Motta');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Earl Boen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Dick Miller');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('50','Bill Paxton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Uma Thurman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Lucy Liu');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Daryl Hannah');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Vivica A. Fox');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Sonny Chiba');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Chiaki Kuriyama');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Michael Bowen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Julie Dreyfus');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Michael Parks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','David Carradine');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('51','Michael Madsen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Vivien Leigh');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Clark Gable');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Olivia de Havilland');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Leslie Howard');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Hattie McDaniel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Thomas Mitchell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Barbara O''Neil');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Butterfly McQueen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Ona Munson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Ann Rutherford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('52','Evelyn Keyes');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Ivana Baquero');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Sergi LÃ³pez');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Maribel VerdÃº');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Doug Jones');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Ariadna Gil');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Ã?lex Angulo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Federico Luppi');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Roger Casamajor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Fernando Tielve');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('53','Pepa Pedroche');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('54','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('55','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Al Pacino');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Michelle Pfeiffer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Steven Bauer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Mary Elizabeth Mastrantonio');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Robert Loggia');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','F. Murray Abraham');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Miriam Colon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Harris Yulin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('56','Paul Shenar');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Naomi Watts');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Adrien Brody');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Jack Black');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Thomas Kretschmann');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Jamie Bell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Lobo Chan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Kyle Chandler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Colin Hanks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Evan Parke');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Andy Serkis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('57','Ray Woolf');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Charlton Heston');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Jack Hawkins');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Stephen Boyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Haya Harareet');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Hugh Griffith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Martha Scott');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Cathy O''Donnell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Sam Jaffe');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Frank Thring');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Terence Longdon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','George Relph');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','AndrÃ© Morell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('58','Finlay Currie');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','Sean Connery');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','Alison Doody');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','Denholm Elliott');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','River Phoenix');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','John Rhys-Davies');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','Julian Glover');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','Bradley Gregg');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('59','Andre Gregory');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Leonardo DiCaprio');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Matt Damon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Jack Nicholson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Mark Wahlberg');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Alec Baldwin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Martin Sheen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Ray Winstone');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Vera Farmiga');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('60','Anthony Anderson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('61','Tom Cruise');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Brad Pitt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Christian Slater');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Antonio Banderas');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Stephen Rea');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Kirsten Dunst');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Domiziana Giordano');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Sara Stockbridge');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Thandie Newton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Christian Bale');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Liam Neeson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Katie Holmes');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Cillian Murphy');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Michael Caine');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Morgan Freeman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Gary Oldman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Ken Watanabe');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Tom Wilkinson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Rutger Hauer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Mark Boone Junior');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Linus Roache');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Rade Serbedzija');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Richard Brake');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Christine Adams');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('62','Jack Gleeson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','Karen Allen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','Paul Freeman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','Ronald Lacey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','John Rhys-Davies');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','Denholm Elliott');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','Wolf Kahler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('63','Alfred Molina');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Ewan McGregor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Natalie Portman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Hayden Christensen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Samuel L. Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Ian McDiarmid');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Ahmed Best');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Anthony Daniels');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Frank Oz');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Andrew Secombe');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Silas Carson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Kenny Baker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Christopher Lee');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Jimmy Smits');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Peter Mayhew');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Keisha Castle-Hughes');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Trisha Noble');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Bruce Spence');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('64','Temuera Morrison');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('65','Sigourney Weaver');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('65','John Hurt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('65','Yaphet Kotto');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('65','Tom Skerritt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('65','Veronica Cartwright');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('65','Harry Dean Stanton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('65','Ian Holm');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('66','Clint Eastwood');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('66','Lee Van Cleef');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('66','Eli Wallach');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('66','Aldo GiuffrÃ¨');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('66','Mario Brega');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('66','Luigi Scarchilli');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('66','Rada Rassimov');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','Mark Hamill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','Carrie Fisher');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','Alec Guinness');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','Billy Dee Williams');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','Anthony Daniels');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','David Prowse');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('67','Kenny Baker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Al Pacino');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Diane Keaton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Andy GarcÃ­a');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Joe Mantegna');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Talia Shire');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Eli Wallach');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Sofia Coppola');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','George Hamilton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Raf Vallone');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Bridget Fonda');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Helmut Berger');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','John Savage');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('68','Franco Citti');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Mark Hamill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Carrie Fisher');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Billy Dee Williams');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Anthony Daniels');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Peter Mayhew');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Frank Oz');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Alec Guinness');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Kenny Baker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Sebastian Shaw');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Warwick Davis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('69','Dave Prowse');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Jack Black');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Joan Cusack');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Mike White');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Sarah Silverman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Joey Gaydos');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Miranda Cosgrove');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Maryam Hassan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Kevin Alexander Clark');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Rebecca Brown');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Robert Tsai');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Caitlin Hale');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Aleisha Allen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Brian Falduto');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Zachary Infante');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','James Hosey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Angelo Massagli');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Cole Hawkins');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('70','Veronica Afflerbach');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('71','Charlton Heston');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('71','Roddy McDowall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('71','Kim Hunter');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('71','Maurice Evans');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('71','James Whitmore');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('71','James Daly');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('71','Linda Harrison');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('72','Sylvester Stallone');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('72','Richard Crenna');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('72','Brian Dennehy');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('72','David Caruso');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('72','Jack Starrett');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('72','Michael Talbott');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('72','Chris Mulkey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Matthew Modine');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Vincent D''Onofrio');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','R. Lee Ermey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Adam Baldwin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Dorian Harewood');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Arliss Howard');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Kevyn Major Howard');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Ed O''Ross');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Gary Landon Mills');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Sal LÃ³pez');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','John Stafford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Kieron Jecchinis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Ngc Le');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('73','Papillon Soo Soo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('74','Roy Scheider');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('74','Robert Shaw');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('74','Richard Dreyfuss');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('74','Lorraine Gary');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('74','Murray Hamilton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('74','Carl Gottlieb');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('74','Jeffrey C. Kramer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Jean Reno');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Natalie Portman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Gary Oldman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Danny Aiello');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Samy Nacery');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Peter Apple');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Michael Badalucco');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Ellen Greene');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','Elizabeth Regen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('75','MaÃ¯wenn Le Besco');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Kevin Spacey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Annette Bening');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Thora Birch');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Allison Janney');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Peter Gallagher');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Mena Suvari');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Wes Bentley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Chris Cooper');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Scott Bakula');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Sam Robards');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('76','Barry Del Sherman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Humphrey Bogart');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Ingrid Bergman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Paul Henreid');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Claude Rains');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Conrad Veidt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Sydney Greenstreet');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Peter Lorre');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','S.Z. Sakall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Madeleine LeBeau');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Dooley Wilson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Joy Page');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','John Qualen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Leonid Kinskey');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('77','Curt Bois');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Audrey Tautou');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Mathieu Kassovitz');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Rufus');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Lorella Cravotta');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Serge Merlin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Jamel Debbouze');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Claire Maurier');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Clotilde Mollet');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Isabelle Nanty');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Dominique Pinon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Artus de Penguern');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Yolande Moreau');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Urbain Cancelier');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('78','Maurice Benichou');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('79','Ewan McGregor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('79','Robert Carlyle');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('79','Jonny Lee Miller');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('79','Ewen Bremner');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('79','Kelly MacDonald');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('79','Kevin McKidd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('79','Peter Mullan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Robert De Niro');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Cybill Shepherd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Jodie Foster');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Albert Brooks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Harvey Keitel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Peter Boyle');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Leonard Harris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('80','Martin Scorsese');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','Jack Nicholson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','Louise Fletcher');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','William Redfield');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','Will Sampson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','Brad Dourif');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','Christopher Lloyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','Danny DeVito');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('81','Scatman Crothers');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Uma Thurman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','David Carradine');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Michael Madsen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Daryl Hannah');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Gordon Liu');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Michael Parks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Bo Svenson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Christopher Allen Nelson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Sid Haig');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('82','Samuel L. Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Tobey Maguire');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Kirsten Dunst');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Alfred Molina');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','James Franco');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Elizabeth Banks');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Bruce Campbell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Rosemary Harris');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','J.K. Simmons');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Vanessa Ferlito');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Emily Deschanel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('83','Stan Lee');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Hugh Jackman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Patrick Stewart');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Brian Cox');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Ian McKellen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Halle Berry');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Anna Paquin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Famke Janssen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','James Marsden');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Rebecca Romijn-Stamos');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Alan Cumming');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Aaron Stanford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Shawn Ashmore');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Kelly Hu');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Bruce Davison');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Katie Stuart');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Kea Wong');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Cotter Smith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Bryce Hodgson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Shauna Kain');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Ty Olsson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Daniel Cudmore');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','James Kirk');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Jill Teed');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('84','Alf Humphreys');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Shia LaBeouf');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Megan Fox');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Jon Voight');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','John Turturro');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Josh Duhamel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Tyrese Gibson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Bernie Mac');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Michael O''Neill');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Julie White');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Rachael Taylor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Kevin Dunn');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Amaury Nolasco');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Ronnie Sperling');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('85','Anthony Anderson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Liam Neeson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Ewan McGregor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Natalie Portman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Jake Lloyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Samuel L. Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Ian McDiarmid');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Anthony Daniels');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Kenny Baker');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Pernilla August');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Frank Oz');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Ray Park');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Terence Stamp');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('86','Keira Knightley');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Sean Young');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Daryl Hannah');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Rutger Hauer');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Edward James Olmos');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Joanna Cassidy');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Brion James');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('87','Joe Turkel');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Martin Sheen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Marlon Brando');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Robert Duvall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Laurence Fishburne');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Frederic Forrest');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Sam Bottoms');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Albert Hall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Dennis Hopper');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','G.D Spradlin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('88','Colleen Camp');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Jack Nicholson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Helen Hunt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Greg Kinnear');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Cuba Gooding Jr.');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Skeet Ulrich');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Shirley Knight');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Jesse James');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Lawrence Kasdan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Yeardley Smith');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Lupe Ontiveros');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Maya Rudolph');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Tara Subkoff');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Lisa Edelstein');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Jamie Kennedy');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Harold Ramis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('89','Julie Benz');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','John Cleese');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Michael Palin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Graham Chapman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Eric Idle');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Terry Jones');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Terry Gilliam');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Sue Jones-Davies');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Carol Cleveland');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('90','Terence Bayler');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('91','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Bill Murray');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Sigourney Weaver');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Dan Aykroyd');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Harold Ramis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Rick Moranis');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','William Atherton');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Annie Potts');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Ernie Hudson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('92','Reginald VelJohnson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('93','Johnny Depp');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('93','Helena Bonham Carter');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('93','Sacha Baron Cohen');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('93','Alan Rickman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('93','Timothy Spall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','George Clooney');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Julia Roberts');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Matt Damon');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Andy GarcÃ­a');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Brad Pitt');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Casey Affleck');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Scott Caan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Elliott Gould');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Bernie Mac');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Carl Reiner');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Don Cheadle');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Topher Grace');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Joshua Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Holly Marie Combs');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('94','Shane West');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('95','Animada');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('96','Arnold Schwarzenegger');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('96','Carl Weathers');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('96','Elpidia Carrillo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('96','Bill Duke');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('96','Kevin Peter Hall');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('96','Sonny Landham');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('96','R.G. Armstrong');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','Harrison Ford');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','Kate Capshaw');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','Jonathan Ke Quan');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','Amrish Puri');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','Philip Stone');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','Roshan Seth');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','David Yip');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('97','Ric Young');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Robert De Niro');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Ray Liotta');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Joe Pesci');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Lorraine Bracco');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Samuel L. Jackson');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Paul Sorvino');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Debi Mazar');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Mike Starr');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Tony Darrow');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Frank Sivero');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Frank Vincent');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Chuck Low');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Frank DiLeo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Clem Caserta');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Illeana Douglas');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Melissa Prophet');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Michael Imperioli');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('98','Tobin Bell');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','Nicole Kidman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','Ewan McGregor');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','John Leguizamo');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','Jim Broadbent');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','Richard Roxburgh');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','David Wenham');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','Jacek Koman');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('99','Kylie Minogue');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','Anthony Perkins');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','Janet Leigh');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','John Gavin');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','Vera Miles');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','John McIntire');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','Martin Balsam');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','Simon Oakland');
Insert into SYSTEM.REPARTO (ID_PELICULA,ACTOR) values ('100','Patricia Hitchcock');

--select * from peliculas p inner join reparto r on p.id=r.id_pelicula where p.pelicula='Titanic';
select p.pelicula,año_estreno,director, f.actores from peliculas p inner join (select p.pelicula,listagg(r.actor,', ') within group (order by r.actor) actores  from peliculas p inner join reparto r on p.id=r.id_pelicula where p.pelicula= 'Titanic' group by p.pelicula) f on p.pelicula=f.pelicula;
select * from peliculas p inner join reparto r on p.id=r.id_pelicula where r.actor='Harrison Ford';
select * from (SELECT director, COUNT(director) FROM peliculas GROUP BY director having count (director)>1 ORDER BY count(director) desc) WHERE rownum <= 10;
select count(distinct actor)from reparto;
select * from peliculas where año_estreno between 1990 and 1999 order by pelicula;
select p.pelicula,año_estreno,director, f.actores from peliculas p inner join (select p.pelicula,listagg(r.actor,', ') within group (order by r.actor) actores  from peliculas p inner join reparto r on p.id=r.id_pelicula where p.año_estreno=2001 group by p.pelicula) f on p.pelicula=f.pelicula;
select p.pelicula,listagg(r.actor,', ') within group (order by r.actor)"actores" from peliculas p inner join reparto r on p.id=r.id_pelicula where p.año_estreno=(SELECT MAX(año_estreno) FROM PELICULAS) group by p.pelicula;

